'use client';
import { useEffect, useState } from 'react';
import { CalendarHeart, Sparkles } from 'lucide-react';
import PageShell from '@/components/PageShell';
import { useRouter } from 'next/navigation';
import { sendInterest } from '@/lib/firestore';
import { useAuth } from '@/lib/auth-context';
import { fetchSearchPool, listenInterestStates, listenShortlist, type InterestState } from '@/lib/firestore';
import { rankByCompatibility } from '@/lib/matrimony';
import type { Profile } from '@/lib/types';
const hash = (s: string) => Array.from(s).reduce((n,c) => (n * 31 + c.charCodeAt(0)) >>> 0, 7);
export default function DailyMatchesPage() {
  const router=useRouter(); const { user, profile } = useAuth(); const [items,setItems]=useState<Profile[]>([]); const [states,setStates]=useState<Record<string,InterestState>>({}); const [shortlist,setShortlist]=useState<Set<string>>(new Set()); const [loading,setLoading]=useState(true);
  useEffect(() => { if (!user || !profile) return; setLoading(true); const u=listenInterestStates(user.uid,setStates); fetchSearchPool(profile).then(pool => { const ranked=rankByCompatibility(pool,profile); const seed=Number(new Date().toISOString().slice(0,10).replace(/-/g,'')); setItems(ranked.sort((a,b)=>(((seed+hash(a.uid))%1000)-((seed+hash(b.uid))%1000))).slice(0,12)); }).finally(()=>setLoading(false)); return u; }, [user,profile]);
  useEffect(() => { if (!user) return; return listenShortlist(user.uid,xs=>setShortlist(new Set(xs.map(x=>x.target)))); },[user]);
  return <PageShell title="Daily curated matches"><div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-4"><p className="flex items-center gap-2 font-extrabold"><CalendarHeart size={18} color="var(--primary)" /> Today&apos;s shortlist</p><p className="mt-1 text-xs text-[var(--muted)]">Curated from compatibility, preferences, profile quality and recent activity. The set refreshes daily.</p></div>{loading?<p className="p-6 text-center text-sm text-[var(--muted)]">Curating matches…</p>:items.length===0?<p className="p-6 text-center text-sm text-[var(--muted)]">Complete more preferences to get curated matches.</p>:<div className="mt-4 grid gap-3">{items.map(p=><article key={p.uid} className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--card)]"><button onClick={()=>router.push(`/user/${p.uid}`)} className="flex w-full gap-3 p-3 text-left"><img src={p.images?.[0]} alt="" className="h-28 w-24 rounded-xl object-cover" /><span className="min-w-0 flex-1"><span className="block text-lg font-black">{p.name}, {p.age}</span><span className="block text-xs text-[var(--muted)]">{[p.location,p.occupation||p.job,p.motherTongue].filter(Boolean).join(' · ')}</span><span className="mt-2 inline-block rounded-full bg-[var(--inputBg)] px-2 py-1 text-[11px] font-extrabold">{p.religion||'Religion not added'} · {p.maritalStatus||'Marital status not added'}</span></span></button><div className="flex gap-2 border-t border-[var(--border)] p-3"><button onClick={()=>router.push(`/user/${p.uid}`)} className="flex-1 rounded-xl border border-[var(--border)] py-2 text-xs font-extrabold">View profile</button><button disabled={states[p.uid]?.state==='sent'} onClick={()=>user && sendInterest(user.uid,p.uid,{isPremium:Boolean(profile?.premium)}).then(()=>setStates(x=>({...x,[p.uid]:{state:'sent',status:'pending'}}))).catch(e=>alert(e instanceof Error?e.message:'Could not send interest.'))} className="flex-1 rounded-xl bg-[var(--primary)] py-2 text-xs font-extrabold text-white disabled:opacity-50">{states[p.uid]?.state==='sent'?'Interest sent':'Send interest'}</button></div></article>)}</div>}<div className="mt-4 flex items-start gap-2 rounded-xl bg-[var(--inputBg)] p-3 text-xs text-[var(--muted)]"><Sparkles size={15} className="mt-0.5 shrink-0" /> Compatibility is a discovery aid, not a promise of relationship success.</div></PageShell>;
}
