// Serves /firebase-messaging-sw.js as a real JS file (not a page). It has to live at the
// origin root so the service worker's default scope covers the whole app.
//
// We generate it on request instead of a static public/ file because the Firebase config
// below is embedded at request time from the same NEXT_PUBLIC_* env vars the client already
// ships in its bundle (these values aren't secret — they identify the Firebase project, not
// grant access to it; access is controlled by Firestore/Storage security rules).
export async function GET() {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  const body = `
// Auto-generated by /src/app/firebase-messaging-sw.js/route.ts — do not edit directly.
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

// Fires when a push arrives while the app is closed or backgrounded.
// (While the tab is focused, onMessage() in src/lib/push.ts handles it instead.)
messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || 'Flirty';
  const body = payload.notification?.body || '';
  const url = payload.fcmOptions?.link || payload.data?.url || '/chats';

  self.registration.showNotification(title, {
    body,
    icon: '/next.svg',
    badge: '/next.svg',
    data: { url },
  });
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = event.notification.data?.url || '/chats';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      return self.clients.openWindow(url);
    })
  );
});
`.trim();

  return new Response(body, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'no-cache',
      'Service-Worker-Allowed': '/',
    },
  });
}
