'use client';
import { useEffect, useState } from 'react';
import { Eye, Crown } from 'lucide-react';
import { useRouter } from 'next/navigation';
import PageShell from '@/components/PageShell';
import { useAuth } from '@/lib/auth-context';
import { getProfile, listenViewedMe } from '@/lib/firestore';
import type { Profile, ProfileViewDoc } from '@/lib/types';
export default function WhoViewedMePage(){ const router=useRouter(); const {user,profile}=useAuth(); const [views,setViews]=useState<ProfileViewDoc[]>([]); const [people,setPeople]=useState<Record<string,Profile>>({}); useEffect(()=>{if(!user||!profile?.premium)return;return listenViewedMe(user.uid,setViews)},[user,profile?.premium]); useEffect(()=>{Promise.all(views.map(v=>getProfile(v.viewer).catch(()=>null))).then(ps=>setPeople(Object.fromEntries(ps.filter(Boolean).map(p=>[p!.uid,p!]))))},[views]); if(!profile?.premium)return <PageShell title="Who viewed you"><div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-6 text-center"><Crown size={28} color="var(--primary)" className="mx-auto"/><p className="mt-3 font-black">Who Viewed You is Premium</p><p className="mt-1 text-sm text-[var(--muted)]">See members who recently opened your profile.</p><button onClick={()=>router.push('/premium')} className="mt-4 rounded-xl bg-[var(--primary)] px-5 py-2 text-sm font-extrabold text-white">Upgrade</button></div></PageShell>; return <PageShell title="Who viewed you"><div className="space-y-2">{views.length===0?<p className="p-6 text-center text-sm text-[var(--muted)]">No profile views yet.</p>:views.map(v=>{const p=people[v.viewer];return <button key={v.viewer} onClick={()=>router.push(`/user/${v.viewer}`)} className="flex w-full items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--card)] p-3 text-left"><div className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-full bg-[var(--inputBg)]">{p?.images?.[0]?<img src={p.images[0]} alt="" className="h-full w-full object-cover"/>:<Eye size={18}/>}</div><span className="flex-1"><span className="block font-extrabold">{p?.name||'Member'}</span><span className="text-xs text-[var(--muted)]">Viewed {new Date(v.viewedAt).toLocaleDateString('en-IN')} · {v.count} visit{v.count===1?'':'s'}</span></span></button>})}</div></PageShell> }
